
%% STANDARD ATMOSPHERE
h0 = Aircraft.Standard_atmosphere.Sea_level.h.value;
[T0, a0, p0, rho0] = atmosisa(h0);
fprintf("--------------------------------------");
fprintf('\n');
fprintf("--------------------------------------");
fprintf('\n');
fprintf("### Standard atmosphere - Sea Level ###");
fprintf('\n');
fprintf("--------------------------------------");
fprintf('\n');
fprintf('Temperature [K]: ');
fprintf('%5.4f%', T0);
fprintf('\n');
fprintf('Speed of sound [m/s]: ');
fprintf('%5.4f%', a0);
fprintf('\n');
fprintf('Pressure [Pa]: ');
fprintf('%5.4f%', p0);
fprintf('\n'); 
fprintf('Density [kg/m^3]: ');
fprintf('%5.4f%', rho0);
fprintf('\n');
fprintf("--------------------------------------"); 
fprintf('\n');
Aircraft.Standard_atmosphere.Sea_level.rho.value                      = rho0;
Aircraft.Standard_atmosphere.Sea_level.rho.Attributes.unit            = "kg/m^3";
Aircraft.Standard_atmosphere.Sea_level.T.value                        = T0; 
Aircraft.Standard_atmosphere.Sea_level.T.Attributes.unit              = 'Kelvin'; 
Aircraft.Standard_atmosphere.Sea_level.p.value                        = p0; 
Aircraft.Standard_atmosphere.Sea_level.p.Attributes.unit              = 'Pa';
Aircraft.Standard_atmosphere.Sea_level.Speed_of_sound.value           = a0; 
Aircraft.Standard_atmosphere.Sea_level.Speed_of_sound.Attributes.unit = "m/s";
% -------------------------------------------------------------------------

h_operative = Aircraft.Standard_atmosphere.Operative_ceiling.h.value;
[T_operative, a_operative, p_operative, rho_operative] = atmosisa(h_operative);
fprintf("--------------------------------------");
fprintf('\n');
fprintf("--------------------------------------");
fprintf('\n');
fprintf("### Standard atmosphere - Operative Ceiling ###");
fprintf('\n');
fprintf("--------------------------------------");
fprintf('\n');
fprintf('Temperature [K]: ');
fprintf('%5.4f%', T_operative);
fprintf('\n');
fprintf('Speed of sound [m/s]: ');
fprintf('%5.4f%', a_operative);
fprintf('\n');
fprintf('Pressure [Pa]: ');
fprintf('%5.4f%', p_operative);
fprintf('\n'); 
fprintf('Density [kg/m^3]: ');
fprintf('%5.4f%', rho_operative);
fprintf('\n');
fprintf("--------------------------------------"); 
fprintf('\n');
Aircraft.Standard_atmosphere.Operative_ceiling.rho.value                      = rho_operative;
Aircraft.Standard_atmosphere.Operative_ceiling.rho.Attributes.unit            = "kg/m^3";
Aircraft.Standard_atmosphere.Operative_ceiling.T.value                        = T_operative; 
Aircraft.Standard_atmosphere.Operative_ceiling.T.Attributes.unit              = 'K'; 
Aircraft.Standard_atmosphere.Operative_ceiling.p.value                        = p_operative; 
Aircraft.Standard_atmosphere.Operative_ceiling.p.Attributes.unit              = 'Pa';
Aircraft.Standard_atmosphere.Operative_ceiling.Speed_of_sound.value           = a_operative; 
Aircraft.Standard_atmosphere.Operative_ceiling.Speed_of_sound.Attributes.unit = "m/s";
% -------------------------------------------------------------------------

h_theoretical = Aircraft.Standard_atmosphere.Theoretical_ceiling.h.value;
[T_theoretical, a_theoretical, p_theoretical, rho_theoretical] = atmosisa(h_theoretical);
fprintf("--------------------------------------");
fprintf('\n');
fprintf("--------------------------------------");
fprintf('\n');
fprintf("### Standard atmosphere - Theoretical Ceiling ###");
fprintf('\n');
fprintf("--------------------------------------");
fprintf('\n');
fprintf('Temperature [K]: ');
fprintf('%5.4f%', T_theoretical);
fprintf('\n');
fprintf('Speed of sound [m/s]: ');
fprintf('%5.4f%', a_theoretical);
fprintf('\n');
fprintf('Pressure [Pa]: ');
fprintf('%5.4f%', p_theoretical);
fprintf('\n'); 
fprintf('Density [kg/m^3]: ');
fprintf('%5.4f%', rho_theoretical);
fprintf('\n');
fprintf("--------------------------------------"); 
fprintf('\n');
Aircraft.Standard_atmosphere.Theoretical_ceiling.rho.value                      = rho_theoretical;
Aircraft.Standard_atmosphere.Theoretical_ceiling.rho.Attributes.unit            = "kg/m^3";
Aircraft.Standard_atmosphere.Theoretical_ceiling.T.value                        = T_theoretical; 
Aircraft.Standard_atmosphere.Theoretical_ceiling.T.Attributes.unit              = 'K'; 
Aircraft.Standard_atmosphere.Theoretical_ceiling.p.value                        = p_theoretical; 
Aircraft.Standard_atmosphere.Theoretical_ceiling.p.Attributes.unit              = 'Pa';
Aircraft.Standard_atmosphere.Theoretical_ceiling.Speed_of_sound.value           = a_theoretical; 
Aircraft.Standard_atmosphere.Theoretical_ceiling.Speed_of_sound.Attributes.unit = "m/s";
